// realTimeEngine.js - Real-time transit simulation, data persistence, and fleet telemetry

export const CAMPUS_STOPS = [
  'Main Gate',
  'Central Library',
  'Engineering Block',
  'Data Centre',
  'Hostel Block A',
  'Girls Hostel',
  'Sports Complex',
  'Food Court',
  'Parking Lot B',
  'Administration Block',
];

export const STOP_COORDINATES = {
  'Main Gate': { x: 100, y: 340 },
  'Central Library': { x: 260, y: 170 },
  'Engineering Block': { x: 450, y: 120 },
  'Data Centre': { x: 630, y: 180 },
  'Hostel Block A': { x: 180, y: 440 },
  'Girls Hostel': { x: 360, y: 470 },
  'Sports Complex': { x: 740, y: 300 },
  'Food Court': { x: 520, y: 340 },
  'Parking Lot B': { x: 670, y: 450 },
  'Administration Block': { x: 370, y: 270 },
};

export const INITIAL_DRIVERS = [
  {
    id: 'drv-1',
    name: 'Samuel Jones',
    phone: '+1-415-555-0101',
    status: 'Online',
    rating: 4.8,
    vehicleNumber: 'NB-003-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    startDutyHour: 6.0,
    endDutyHour: 20.0,
    blocks: [
      { id: 'blk-1-1', type: 'DUTY_START', startHour: 6.0, endHour: 7.0, label: 'Start Duty', pickups: 0, drops: 0, vehicleNumber: 'NB-003-RF', notes: 'Shift Start' },
      { id: 'blk-1-2', type: 'TRIP', startHour: 8.0, endHour: 12.0, label: '2 Pickup 3 Drop', pickups: 2, drops: 3, vehicleNumber: 'NB-003-RF', notes: 'Library to Data Centre' },
      { id: 'blk-1-3', type: 'BREAK', startHour: 13.0, endHour: 14.5, label: 'Lunch Break', pickups: 0, drops: 0, vehicleNumber: 'NB-003-RF', notes: 'Designated Canteen Rest' },
      { id: 'blk-1-4', type: 'EMPTY_LEG', startHour: 15.0, endHour: 16.0, label: 'Empty Leg', pickups: 0, drops: 0, vehicleNumber: 'NB-003-RF', notes: 'Depot Relocation' },
      { id: 'blk-1-5', type: 'TRIP', startHour: 16.0, endHour: 19.0, label: '4 Pickup 4 Drop', pickups: 4, drops: 4, vehicleNumber: 'NB-003-RF', notes: 'Hostel to Main Gate' },
      { id: 'blk-1-6', type: 'DUTY_END', startHour: 19.5, endHour: 20.0, label: 'Duty End', pickups: 0, drops: 0, vehicleNumber: 'NB-003-RF', notes: 'Clock Out' },
    ],
  },
  {
    id: 'drv-2',
    name: 'Bob Jones',
    phone: '+1-415-555-0102',
    status: 'Offline',
    rating: 4.6,
    vehicleNumber: 'DL-04-AB-1290',
    vehicleDetails: 'Shuttle Van B4 | 8 Seater',
    startDutyHour: 7.0,
    endDutyHour: 19.0,
    blocks: [
      { id: 'blk-2-1', type: 'DUTY_START', startHour: 7.0, endHour: 7.5, label: 'Start Duty', pickups: 0, drops: 0, vehicleNumber: 'DL-04-AB-1290', notes: 'Morning Prep' },
      { id: 'blk-2-2', type: 'TRIP', startHour: 8.5, endHour: 12.5, label: '3 Pickup 2 Drop', pickups: 3, drops: 2, vehicleNumber: 'DL-04-AB-1290', notes: 'Parking to Engineering' },
      { id: 'blk-2-3', type: 'BREAK', startHour: 13.0, endHour: 14.0, label: 'Break', pickups: 0, drops: 0, vehicleNumber: 'DL-04-AB-1290', notes: 'Rest Period' },
      { id: 'blk-2-4', type: 'VEHICLE_CHANGE', startHour: 14.5, endHour: 15.5, label: 'Vehicle Change', pickups: 0, drops: 0, vehicleNumber: 'DL-04-AB-1290', notes: 'Maintenance swap' },
      { id: 'blk-2-5', type: 'DUTY_END', startHour: 18.5, endHour: 19.0, label: 'Duty End', pickups: 0, drops: 0, vehicleNumber: 'DL-04-AB-1290', notes: 'Shift End' },
    ],
  },
  {
    id: 'drv-3',
    name: 'Jonathan Spikes',
    phone: '+1-415-555-0103',
    status: 'Offline',
    rating: 4.7,
    vehicleNumber: 'KA-05-MN-9921',
    vehicleDetails: 'Campus Cruiser 7 | 15 Seater',
    startDutyHour: 8.0,
    endDutyHour: 21.0,
    blocks: [
      { id: 'blk-3-1', type: 'DUTY_START', startHour: 8.0, endHour: 8.5, label: 'Start Duty', pickups: 0, drops: 0, vehicleNumber: 'KA-05-MN-9921', notes: 'Inspection' },
      { id: 'blk-3-2', type: 'TRIP', startHour: 9.5, endHour: 13.0, label: '2 Pickup 3 Drop', pickups: 2, drops: 3, vehicleNumber: 'KA-05-MN-9921', notes: 'Sports Complex to Cafeteria' },
      { id: 'blk-3-3', type: 'BREAK', startHour: 14.0, endHour: 15.0, label: 'Break', pickups: 0, drops: 0, vehicleNumber: 'KA-05-MN-9921', notes: 'Afternoon Break' },
      { id: 'blk-3-4', type: 'TRIP', startHour: 16.5, endHour: 20.0, label: '5 Pickup 3 Drop', pickups: 5, drops: 3, vehicleNumber: 'KA-05-MN-9921', notes: 'Evening Campus Loop' },
      { id: 'blk-3-5', type: 'DUTY_END', startHour: 20.5, endHour: 21.0, label: 'Duty End', pickups: 0, drops: 0, vehicleNumber: 'KA-05-MN-9921', notes: 'Turn in keys' },
    ],
  },
  {
    id: 'drv-4',
    name: 'Steve Smith',
    phone: '+1-322-493-3292',
    status: 'Online',
    rating: 4.5,
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    startDutyHour: 7.0,
    endDutyHour: 19.0,
    blocks: [
      { id: 'blk-4-1', type: 'DUTY_START', startHour: 7.0, endHour: 7.5, label: 'Start Duty', pickups: 0, drops: 0, vehicleNumber: 'NB-002-RF', notes: 'Clock In' },
      { id: 'blk-4-2', type: 'TRIP', startHour: 8.0, endHour: 11.5, label: '4 Pickup 2 Drop', pickups: 4, drops: 2, vehicleNumber: 'NB-002-RF', notes: 'Library & Data Centre Loop' },
      { id: 'blk-4-3', type: 'TRIP', startHour: 11.5, endHour: 14.0, label: '3 Pickup 3 Drop', pickups: 3, drops: 3, vehicleNumber: 'NB-002-RF', notes: 'Thompson Booking 123123' },
      { id: 'blk-4-4', type: 'BREAK', startHour: 14.5, endHour: 15.5, label: 'Break', pickups: 0, drops: 0, vehicleNumber: 'NB-002-RF', notes: 'Afternoon rest' },
      { id: 'blk-4-5', type: 'TRIP', startHour: 16.0, endHour: 18.5, label: '2 Pickup 4 Drop', pickups: 2, drops: 4, vehicleNumber: 'NB-002-RF', notes: 'Late Afternoon Transit' },
    ],
  },
  {
    id: 'drv-5',
    name: 'Anita Sharma',
    phone: '+1-415-555-0105',
    status: 'Online',
    rating: 4.9,
    vehicleNumber: 'MH-12-PQ-4412',
    vehicleDetails: 'Green Electric MiniBus | 16 Seater',
    startDutyHour: 6.0,
    endDutyHour: 16.0,
    blocks: [
      { id: 'blk-5-1', type: 'DUTY_START', startHour: 6.0, endHour: 6.5, label: 'Start Duty', pickups: 0, drops: 0, vehicleNumber: 'MH-12-PQ-4412', notes: 'Battery check' },
      { id: 'blk-5-2', type: 'TRIP', startHour: 7.0, endHour: 11.0, label: '6 Pickup 5 Drop', pickups: 6, drops: 5, vehicleNumber: 'MH-12-PQ-4412', notes: 'Hostel to Main Academic Gate' },
      { id: 'blk-5-3', type: 'BREAK', startHour: 11.5, endHour: 12.5, label: 'Break', pickups: 0, drops: 0, vehicleNumber: 'MH-12-PQ-4412', notes: 'Recharging break' },
      { id: 'blk-5-4', type: 'TRIP', startHour: 13.0, endHour: 15.5, label: '3 Pickup 3 Drop', pickups: 3, drops: 3, vehicleNumber: 'MH-12-PQ-4412', notes: 'Research Park Loop' },
    ],
  },
  {
    id: 'drv-6',
    name: 'Priya Patel',
    phone: '+1-415-555-0106',
    status: 'Online',
    rating: 4.8,
    vehicleNumber: 'UP-32-BZ-8821',
    vehicleDetails: 'City Runner 3 | 10 Seater',
    startDutyHour: 9.0,
    endDutyHour: 22.0,
    blocks: [
      { id: 'blk-6-1', type: 'DUTY_START', startHour: 9.0, endHour: 9.5, label: 'Start Duty', pickups: 0, drops: 0, vehicleNumber: 'UP-32-BZ-8821', notes: 'Morning check' },
      { id: 'blk-6-2', type: 'TRIP', startHour: 10.0, endHour: 14.0, label: '4 Pickup 4 Drop', pickups: 4, drops: 4, vehicleNumber: 'UP-32-BZ-8821', notes: 'Central Ring Route' },
      { id: 'blk-6-3', type: 'BREAK', startHour: 14.5, endHour: 15.5, label: 'Break', pickups: 0, drops: 0, vehicleNumber: 'UP-32-BZ-8821', notes: 'Lunch' },
      { id: 'blk-6-4', type: 'TRIP', startHour: 16.0, endHour: 21.0, label: '7 Pickup 6 Drop', pickups: 7, drops: 6, vehicleNumber: 'UP-32-BZ-8821', notes: 'Evening Library & Lab Rush' },
    ],
  },
];

export const INITIAL_ROUTES = [
  {
    id: 'rt-1',
    name: 'Central Campus Express',
    code: 'CCE-01',
    stops: ['Main Gate', 'Central Library', 'Engineering Block', 'Data Centre', 'Sports Complex'],
    estimatedMinutes: 18,
    distanceKm: 4.2,
    assignedVehicle: 'NB-002-RF',
    assignedDriverId: 'drv-4',
    frequency: 'Every 8 mins',
    isActive: true,
    color: '#10b981',
  },
  {
    id: 'rt-2',
    name: 'Hostel Ring Shuttle',
    code: 'HRS-02',
    stops: ['Girls Hostel', 'Hostel Block A', 'Food Court', 'Sports Complex', 'Main Gate'],
    estimatedMinutes: 15,
    distanceKm: 3.5,
    assignedVehicle: 'MH-12-PQ-4412',
    assignedDriverId: 'drv-5',
    frequency: 'Every 10 mins',
    isActive: true,
    color: '#3b82f6',
  },
  {
    id: 'rt-3',
    name: 'Research & Tech Park Loop',
    code: 'RTP-03',
    stops: ['Parking Lot B', 'Data Centre', 'Engineering Block', 'Administration Block', 'Central Library'],
    estimatedMinutes: 22,
    distanceKm: 5.1,
    assignedVehicle: 'KA-05-MN-9921',
    assignedDriverId: 'drv-3',
    frequency: 'Every 15 mins',
    isActive: true,
    color: '#8b5cf6',
  },
  {
    id: 'rt-4',
    name: 'Night Owl Campus Line',
    code: 'NOC-04',
    stops: ['Central Library', 'Food Court', 'Hostel Block A', 'Girls Hostel', 'Main Gate'],
    estimatedMinutes: 25,
    distanceKm: 6.0,
    assignedVehicle: 'UP-32-BZ-8821',
    assignedDriverId: 'drv-6',
    frequency: 'Every 20 mins',
    isActive: true,
    color: '#f59e0b',
  },
];

export const INITIAL_BOOKINGS = [
  {
    id: '123123',
    employeeName: 'Thompson',
    employeeId: 'EMP-123123',
    status: 'On Going',
    fromLocation: 'Central Library',
    toLocation: 'Data Centre',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '11:21',
    pickupTime: '11:25',
    plannedDropTime: '11:32',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Steve Smith',
    driverPhone: '+1-322-493-3292',
    driverRating: 4.5,
    notes: 'Please report at Front Desk',
    delayMinutes: 5,
    role: 'Student',
  },
  {
    id: '324235',
    employeeName: 'Daniel Radcliff',
    employeeId: 'EMP-324235',
    status: 'Waiting',
    fromLocation: 'Central Library',
    toLocation: 'Parking Lot B',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '11:34',
    pickupTime: '-',
    plannedDropTime: '11:43',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Steve Smith',
    driverPhone: '+1-322-493-3292',
    driverRating: 4.5,
    notes: 'Requires front seat access',
    delayMinutes: 0,
    role: 'Student',
  },
  {
    id: '545232',
    employeeName: 'W.J. Smith',
    employeeId: 'EMP-545232',
    status: 'No Show',
    fromLocation: 'Data Centre',
    toLocation: 'Parking Lot B',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '11:50',
    pickupTime: '-',
    plannedDropTime: '12:10',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Samuel Jones',
    driverPhone: '+1-415-555-0101',
    driverRating: 4.8,
    notes: 'Passenger did not arrive at pickup pillar #3',
    delayMinutes: 0,
    role: 'Staff',
  },
  {
    id: '434532',
    employeeName: 'Tina Shah',
    employeeId: 'EMP-434532',
    status: 'Declined',
    fromLocation: 'Central Library',
    toLocation: 'Data Centre',
    vehicleNumber: '-',
    vehicleDetails: 'Shuttle Capacity Full',
    requestedPickupTime: '11:55',
    pickupTime: '-',
    plannedDropTime: '12:15',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Unassigned',
    driverPhone: '-',
    driverRating: 0.0,
    notes: 'Declined due to peak passenger capacity exceeded',
    delayMinutes: 0,
    role: 'Staff',
  },
  {
    id: '545233',
    employeeName: 'W.J. Smith',
    employeeId: 'EMP-545232',
    status: 'Completed',
    fromLocation: 'Data Centre',
    toLocation: 'Parking Lot B',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '11:58',
    pickupTime: '12:25',
    plannedDropTime: '12:35',
    actualDropTime: '12:40',
    date: 'Dec 16, 2024',
    driverName: 'Steve Smith',
    driverPhone: '+1-322-493-3292',
    driverRating: 4.5,
    notes: 'Regular commute',
    delayMinutes: 5,
    role: 'Staff',
  },
  {
    id: '434533',
    employeeName: 'Tina Shah',
    employeeId: 'EMP-434532',
    status: 'Requested',
    fromLocation: 'Central Library',
    toLocation: 'Data Centre',
    vehicleNumber: '-',
    vehicleDetails: 'Awaiting Vehicle Assignment',
    requestedPickupTime: '11:55',
    pickupTime: '-',
    plannedDropTime: '12:15',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Unassigned',
    driverPhone: '-',
    driverRating: 0.0,
    notes: 'Priority booking for faculty seminar',
    delayMinutes: 0,
    role: 'Staff',
  },
  {
    id: '545234',
    employeeName: 'Prof. Alok Gupta',
    employeeId: 'FAC-881204',
    status: 'Accepted',
    fromLocation: 'Engineering Block',
    toLocation: 'Administration Block',
    vehicleNumber: 'MH-12-PQ-4412',
    vehicleDetails: 'Green Electric MiniBus | 16 Seater',
    requestedPickupTime: '12:10',
    pickupTime: '12:12',
    plannedDropTime: '12:22',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Anita Sharma',
    driverPhone: '+1-415-555-0105',
    driverRating: 4.9,
    notes: 'HOD Academic Senate Conference',
    delayMinutes: 0,
    role: 'Staff',
  },
  {
    id: '601004',
    employeeName: 'Navin Patidar',
    employeeId: 'EMP-601004',
    status: 'Accepted',
    fromLocation: 'Food Court',
    toLocation: 'Sports Complex',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '12:15',
    pickupTime: '12:18',
    plannedDropTime: '12:30',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Steve Smith',
    driverPhone: '+1-322-493-3292',
    driverRating: 4.5,
    notes: 'Sports equipment gear baggage',
    delayMinutes: 2,
    role: 'Student',
  },
  {
    id: '601005',
    employeeName: 'Sukhdev Ahari',
    employeeId: 'EMP-601005',
    status: 'Waiting',
    fromLocation: 'Central Library',
    toLocation: 'Hostel Block A',
    vehicleNumber: 'MH-12-PQ-4412',
    vehicleDetails: 'Green Electric MiniBus | 16 Seater',
    requestedPickupTime: '12:20',
    pickupTime: '-',
    plannedDropTime: '12:35',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Anita Sharma',
    driverPhone: '+1-415-555-0105',
    driverRating: 4.9,
    notes: 'Waiting at pickup shelter #2',
    delayMinutes: 0,
    role: 'Student',
  },
  {
    id: '601006',
    employeeName: 'Vinod Dindor',
    employeeId: 'EMP-601006',
    status: 'On Going',
    fromLocation: 'Engineering Block',
    toLocation: 'Data Centre',
    vehicleNumber: 'UP-32-BZ-8821',
    vehicleDetails: 'City Runner 3 | 10 Seater',
    requestedPickupTime: '12:05',
    pickupTime: '12:08',
    plannedDropTime: '12:20',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Priya Patel',
    driverPhone: '+1-415-555-0106',
    driverRating: 4.8,
    notes: 'Lab equipment courier onboard',
    delayMinutes: 0,
    role: 'Student',
  },
  {
    id: '601007',
    employeeName: 'Geetanjali Verma',
    employeeId: 'EMP-601007',
    status: 'Waiting',
    fromLocation: 'Main Gate',
    toLocation: 'Sports Complex',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '12:30',
    pickupTime: '-',
    plannedDropTime: '12:45',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Steve Smith',
    driverPhone: '+1-322-493-3292',
    driverRating: 4.5,
    notes: 'Student athletics squad',
    delayMinutes: 0,
    role: 'Student',
  },
  {
    id: '601008',
    employeeName: 'Jayesh Singh',
    employeeId: 'EMP-601008',
    status: 'Accepted',
    fromLocation: 'Central Library',
    toLocation: 'Administration Block',
    vehicleNumber: 'KA-05-MN-9921',
    vehicleDetails: 'Campus Cruiser 7 | 15 Seater',
    requestedPickupTime: '12:35',
    pickupTime: '12:38',
    plannedDropTime: '12:50',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Jonathan Spikes',
    driverPhone: '+1-415-555-0103',
    driverRating: 4.7,
    notes: 'Faculty transit',
    delayMinutes: 0,
    role: 'Staff',
  },
  {
    id: '601009',
    employeeName: 'Vazral Maru',
    employeeId: 'EMP-601009',
    status: 'Completed',
    fromLocation: 'Food Court',
    toLocation: 'Girls Hostel',
    vehicleNumber: 'MH-12-PQ-4412',
    vehicleDetails: 'Green Electric MiniBus | 16 Seater',
    requestedPickupTime: '10:57',
    pickupTime: '11:00',
    plannedDropTime: '11:15',
    actualDropTime: '11:14',
    date: 'Dec 16, 2024',
    driverName: 'Anita Sharma',
    driverPhone: '+1-415-555-0105',
    driverRating: 4.9,
    notes: 'Evening campus drop',
    delayMinutes: 0,
    role: 'Student',
  },
  {
    id: '601010',
    employeeName: 'Nilesh Pandey',
    employeeId: 'EMP-601010',
    status: 'Cancelled',
    fromLocation: 'Data Centre',
    toLocation: 'Parking Lot B',
    vehicleNumber: 'DL-04-AB-1290',
    vehicleDetails: 'Shuttle Van B4 | 8 Seater',
    requestedPickupTime: '11:00',
    pickupTime: '-',
    plannedDropTime: '11:20',
    actualDropTime: '-',
    date: 'Dec 16, 2024',
    driverName: 'Bob Jones',
    driverPhone: '+1-415-555-0102',
    driverRating: 4.6,
    notes: 'Meeting cancelled',
    delayMinutes: 0,
    role: 'Staff',
  },
  {
    id: '601011',
    employeeName: 'Sanjay Gandhi',
    employeeId: 'EMP-601011',
    status: 'Dropped',
    fromLocation: 'Main Gate',
    toLocation: 'Data Centre',
    vehicleNumber: 'NB-002-RF',
    vehicleDetails: 'UA3282 White Bus | 12 Seater',
    requestedPickupTime: '10:15',
    pickupTime: '10:20',
    plannedDropTime: '10:35',
    actualDropTime: '10:36',
    date: 'Dec 16, 2024',
    driverName: 'Samuel Jones',
    driverPhone: '+1-415-555-0101',
    driverRating: 4.8,
    notes: 'Guest lecturer arrival',
    delayMinutes: 1,
    role: 'Staff',
  },
];

// Helper to load or initialize from localStorage
export const getStoredData = (key, fallback) => {
  try {
    const item = localStorage.getItem(`shuttle_${key}`);
    if (item) return JSON.parse(item);
  } catch (e) {
    console.warn('LocalStorage read error:', e);
  }
  return fallback;
};

export const setStoredData = (key, data) => {
  try {
    localStorage.setItem(`shuttle_${key}`, JSON.stringify(data));
  } catch (e) {
    console.warn('LocalStorage write error:', e);
  }
};

// Simulation Shuttles on live routes
export const INITIAL_LIVE_SHUTTLES = [
  {
    id: 'shuttle-1',
    vehicleNumber: 'NB-002-RF',
    model: 'White Bus | 12 Seater',
    routeId: 'rt-1',
    routeName: 'Central Campus Express',
    driverName: 'Steve Smith',
    driverPhone: '+1-322-493-3292',
    driverRating: 4.5,
    currentStopIndex: 1, // Central Library
    progressToNext: 0.45, // 45% between Central Library and Engineering Block
    speedKmh: 24,
    passengerCount: 7,
    maxCapacity: 12,
    color: '#10b981',
    status: 'In Transit',
  },
  {
    id: 'shuttle-2',
    vehicleNumber: 'MH-12-PQ-4412',
    model: 'Electric MiniBus | 16 Seater',
    routeId: 'rt-2',
    routeName: 'Hostel Ring Shuttle',
    driverName: 'Anita Sharma',
    driverPhone: '+1-415-555-0105',
    driverRating: 4.9,
    currentStopIndex: 2, // Food Court
    progressToNext: 0.72,
    speedKmh: 28,
    passengerCount: 11,
    maxCapacity: 16,
    color: '#3b82f6',
    status: 'In Transit',
  },
  {
    id: 'shuttle-3',
    vehicleNumber: 'KA-05-MN-9921',
    model: 'Campus Cruiser 7 | 15 Seater',
    routeId: 'rt-3',
    routeName: 'Research & Tech Park Loop',
    driverName: 'Jonathan Spikes',
    driverPhone: '+1-415-555-0103',
    driverRating: 4.7,
    currentStopIndex: 0, // Parking Lot B
    progressToNext: 0.15,
    speedKmh: 18,
    passengerCount: 4,
    maxCapacity: 15,
    color: '#8b5cf6',
    status: 'Departing Stop',
  },
  {
    id: 'shuttle-4',
    vehicleNumber: 'UP-32-BZ-8821',
    model: 'City Runner 3 | 10 Seater',
    routeId: 'rt-4',
    routeName: 'Night Owl Campus Line',
    driverName: 'Priya Patel',
    driverPhone: '+1-415-555-0106',
    driverRating: 4.8,
    currentStopIndex: 3, // Girls Hostel
    progressToNext: 0.90,
    speedKmh: 30,
    passengerCount: 6,
    maxCapacity: 10,
    color: '#f59e0b',
    status: 'Approaching Stop',
  },
];
